In [1]:
pip install pm4py

Requirement already satisfied: pm4py in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.7.23.11)
Requirement already satisfied: cvxopt in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (1.3.3)
Requirement already satisfied: graphviz in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (0.21)
Requirement already satisfied: lxml in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (6.1.3)
Requirement already satisfied: matplotlib in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (3.11.2)
Requirement already satisfied: networkx in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (3.6.1)
Requirement already satisfied: numpy in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (2.3.2)
Requirement already satisfied: pandas in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (2.3.1)
Requirement already satisfied: pytz in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (2025.2)
Requirement already satisfied: scipy in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (1.16.1)
Requirement already satisfied: tqdm in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pm4py) (4.70.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (13.0.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->pm4py) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib->pm4py) (1.17.0)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->pm4py) (2025.2)
Requirement already satisfied: colorama in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm->pm4py) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import pm4py

============================================================

  Welcome to PM4Py — Community Version
  Open-Source License (AGPL v3)

  📚 Docs & Examples:
     https://processintelligence.solutions/pm4py

  ⚖️  License: AGPL v3 — Commercial use requires open-sourcing your application.
     Business use without open-sourcing? A commercial license is available:
     https://processintelligence.solutions/pm4py#licensing

============================================================

In [3]:
df = pd.read_csv("cleaned_data")

In [4]:
df

,case_id,activity,timestamp,department,resource
0,HOSP_0001,Patient Registration,2026-03-23 08:54:00,Front Desk,Registration Clerk
1,HOSP_0001,Initial Triage,2026-03-23 09:14:00,Emergency/Triage,Triage Nurse
2,HOSP_0001,Doctor Consultation,2026-03-23 09:19:00,Outpatient,Doctor
3,HOSP_0001,Treatment/Prescription,2026-03-23 09:40:00,Outpatient,Doctor
4,HOSP_0001,Payment Completed,2026-03-23 09:56:00,Billing,Billing Clerk
...,...,...,...,...,...
948,HOSP_0100,Initial Triage,2026-03-22 16:43:00,Emergency/Triage,Triage Nurse
949,HOSP_0100,Doctor Consultation,2026-03-22 16:47:00,Outpatient,Doctor
950,HOSP_0100,Treatment/Prescription,2026-03-22 16:55:00,Outpatient,Doctor
951,HOSP_0100,Payment Completed,2026-03-22 17:12:00,Billing,Billing Clerk
952,HOSP_0100,Patient Discharged,2026-03-22 17:28:00,Outpatient,Nurse

In [5]:
log = pm4py.format_dataframe(df, case_id = 'case_id', activity_key = 'activity', timestamp_key = 'timestamp')

In [6]:
log.head()

,case_id,activity,timestamp,department,resource,case:concept:name,concept:name,time:timestamp,@@index,@@case_index
0,HOSP_0001,Patient Registration,2026-03-23 08:54:00+00:00,Front Desk,Registration Clerk,HOSP_0001,Patient Registration,2026-03-23 08:54:00+00:00,0,0
1,HOSP_0001,Initial Triage,2026-03-23 09:14:00+00:00,Emergency/Triage,Triage Nurse,HOSP_0001,Initial Triage,2026-03-23 09:14:00+00:00,1,0
2,HOSP_0001,Doctor Consultation,2026-03-23 09:19:00+00:00,Outpatient,Doctor,HOSP_0001,Doctor Consultation,2026-03-23 09:19:00+00:00,2,0
3,HOSP_0001,Treatment/Prescription,2026-03-23 09:40:00+00:00,Outpatient,Doctor,HOSP_0001,Treatment/Prescription,2026-03-23 09:40:00+00:00,3,0
4,HOSP_0001,Payment Completed,2026-03-23 09:56:00+00:00,Billing,Billing Clerk,HOSP_0001,Payment Completed,2026-03-23 09:56:00+00:00,4,0

In [7]:
start_activity = pm4py.get_start_activities(log)
end_activity = pm4py.get_end_activities(log)
print("start_activity: ",start_activity)
print("end_activity: ",end_activity)

start_activity:  {'Patient Registration': 100}
end_activity:  {'Patient Discharged': 69, 'Discharge Processed': 31}

In [18]:
import pm4py
from pm4py.visualization.common import gview

# Tell PM4Py to use the matplotlib view engine instead of graphviz
# (Example for a process tree or Petri net visualization)

In [19]:
dfg, first_stage, last_stage = pm4py.discover_dfg(log)

In [20]:
gview.matplotlib_view(pm4py.view_dfg(dfg, first_stage, last_stage))

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

In [21]:
import pm4py
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# 1. Save the DFG visualization to a PNG file
pm4py.save_vis_dfg(dfg, first_stage, last_stage, file_path="dfg_plot.png")

# 2. Load and display the saved image inline using Matplotlib
img = mpimg.imread("dfg_plot.png")
plt.figure(figsize=(12, 8))
plt.imshow(img)
plt.axis('off')
plt.show()

Matplotlib is building the font cache; this may take a moment.

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH